# Generated by Django 5.1.4 on 2025-11-18 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384)),
                ('knoladge', models.TextField(blank=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('addition', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('link', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, default='Unknown', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='NeuralHire__city_940c7a_idx'), models.Index(fields=['money'], name='NeuralHire__money_80431c_idx')],
            },
        ),
    ]
