# Generated by Django 4.0.6 on 2023-01-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('money', models.IntegerField(blank=True)),
                ('knoladge', models.TextField()),
                ('addition', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('link', models.TextField()),
            ],
        ),
    ]
