# Generated by Django 4.0.6 on 2023-01-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralHire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Job',
        ),
    ]
