# Generated by Django 5.1.4 on 2025-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralHire', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='crop_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
