# Generated by Django 5.1.4 on 2025-12-15 14:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralHire', '0003_resume_crop_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='content_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
    ]
